name: server


on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkoutc

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name : injection-yml
        run : echo -E "${{ secrets.YML }}" > ./src/main/resources/application.yml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Execute Gradle build and analyze
        run: ./gradlew jib

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME }}
          script: ${{ secrets.SCRIPT }}
